In [1]:
from mxnet import nd

In [2]:
x = nd.array([3.0])
y = nd.array([2.0])

In [3]:
x + y


[5.]
<NDArray 1 @cpu(0)>

In [4]:
x.asscalar()

3.0

In [6]:
nd.arange(3)


[0. 1. 2.]
<NDArray 3 @cpu(0)>

In [10]:
a = nd.random_normal(0,1, shape=(3,4))
print(a)


[[ 0.4781131   0.9628535   1.7288586   0.42453527]
 [ 1.7228668  -0.32012343 -0.9782294   2.0675595 ]
 [-1.7168009   0.47031024  0.24345131  0.30026805]]
<NDArray 3x4 @cpu(0)>


In [11]:
print(a[:, 3])
print(a[1, :])


[0.42453527 2.0675595  0.30026805]
<NDArray 3 @cpu(0)>

[ 1.7228668  -0.32012343 -0.9782294   2.0675595 ]
<NDArray 4 @cpu(0)>


In [12]:
print(a.reshape((2, 6)))


[[ 0.4781131   0.9628535   1.7288586   0.42453527  1.7228668  -0.32012343]
 [-0.9782294   2.0675595  -1.7168009   0.47031024  0.24345131  0.30026805]]
<NDArray 2x6 @cpu(0)>


In [13]:
a * 2


[[ 0.9562262   1.925707    3.4577172   0.84907055]
 [ 3.4457335  -0.64024687 -1.9564588   4.135119  ]
 [-3.4336019   0.9406205   0.48690262  0.6005361 ]]
<NDArray 3x4 @cpu(0)>

In [14]:
a + a


[[ 0.9562262   1.925707    3.4577172   0.84907055]
 [ 3.4457335  -0.64024687 -1.9564588   4.135119  ]
 [-3.4336019   0.9406205   0.48690262  0.6005361 ]]
<NDArray 3x4 @cpu(0)>

In [15]:
a / a


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [16]:
a / nd.arange(4)


[[        inf  0.9628535   0.8644293   0.14151175]
 [        inf -0.32012343 -0.4891147   0.6891865 ]
 [       -inf  0.47031024  0.12172566  0.10008935]]
<NDArray 3x4 @cpu(0)>

In [18]:
nd.sum(a)


[5.3836627]
<NDArray 1 @cpu(0)>

In [19]:
nd.mean(a)


[0.44863856]
<NDArray 1 @cpu(0)>

In [23]:
nd.dot(a, a.T)


[[ 4.324861   -0.29797506  0.18038209]
 [-0.29797506  8.302484   -2.7257059 ]
 [ 0.18038209 -2.7257059   3.3180263 ]]
<NDArray 3x3 @cpu(0)>

In [15]:
a = nd.random_normal(4, 1, shape=(4, 4))
b = nd.arange(4) + 1
print(a)
print(b)


[[4.478113  4.9628534 5.7288585 4.4245353]
 [5.722867  3.6798766 3.0217705 6.0675592]
 [2.283199  4.47031   4.243451  4.300268 ]
 [5.9079247 4.069608  3.7050653 5.249877 ]]
<NDArray 4x4 @cpu(0)>

[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>


In [16]:
x = nd.dot(nd.linalg.potri(a), b.T)

In [17]:
z


[ 0.0270767  -0.04316258 -0.00297286  0.08548757]
<NDArray 4 @cpu(0)>

In [18]:
nd.dot(a, x)


[0.49750724 0.47213414 0.27824965 0.498399  ]
<NDArray 4 @cpu(0)>

In [19]:
b


[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>