In [ ]:
import mxnet as mx
from mxnet import nd

Add same seed as example

In [2]:
mx.random.seed(1)

In [3]:
print(nd.empty((3, 4)))


[[9.2632829e-35 8.3657518e-43 9.2632869e-35 8.3657518e-43]
 [9.2632869e-35 8.3657518e-43 9.2632875e-35 8.3657518e-43]
 [0.0000000e+00 8.3657518e-43 0.0000000e+00 8.3657518e-43]]
<NDArray 3x4 @cpu(0)>


In [4]:
print(nd.zeros((3, 4)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>


In [5]:
print(nd.ones((3,4)))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [7]:
print(nd.random_normal(0, 1, shape=(3, 4)))


[[-1.306444    0.11287735 -2.6309924  -0.10713575]
 [ 0.31348404 -0.05735846 -1.1105994  -0.5765109 ]
 [-0.22899596  0.57960725  0.8124368   1.0448428 ]]
<NDArray 3x4 @cpu(0)>


In [9]:
print(nd.empty((3, 4)).size)
print(nd.empty((3, 4)).shape)

12
(3, 4)


In [13]:
x = nd.random_normal(0,1, shape=(3, 4))
y = nd.ones((3,4))
print(x)
print(y)


[[ 2.3923352  -1.2233835   0.58519     0.24148573]
 [ 1.0874441  -1.1646322  -0.15579285  0.2778769 ]
 [ 1.3224207   1.6976414   0.24266216  0.39777333]]
<NDArray 3x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [14]:
x + y


[[ 3.3923352  -0.22338355  1.58519     1.2414857 ]
 [ 2.087444   -0.1646322   0.84420717  1.2778769 ]
 [ 2.3224206   2.6976414   1.2426622   1.3977733 ]]
<NDArray 3x4 @cpu(0)>

In [15]:
x * y


[[ 2.3923352  -1.2233835   0.58519     0.24148573]
 [ 1.0874441  -1.1646322  -0.15579285  0.2778769 ]
 [ 1.3224207   1.6976414   0.24266216  0.39777333]]
<NDArray 3x4 @cpu(0)>

In [16]:
nd.dot(x, y.T)


[[1.9956273  1.9956273  1.9956273 ]
 [0.04489593 0.04489593 0.04489593]
 [3.6604974  3.6604974  3.6604974 ]]
<NDArray 3x3 @cpu(0)>

In place operations

In [18]:
print('id(y)', id(y))
y = y + x
print('id(y)', id(y))

id(y) 2564499959648
id(y) 2564504785584


In [19]:
print('id(y)', id(y))
y[:] = y + x
print('id(y)', id(y))

id(y) 2564504785584


id(y) 2564504785584


This directly works over the same memory buffer

In [20]:
nd.elemwise_add(x, y, out=y)


[[10.569341   -3.8935342   3.3407602   1.9659429 ]
 [ 5.3497763  -3.6585288   0.37682867  2.1115074 ]
 [ 6.2896824   7.7905655   1.9706488   2.591093  ]]
<NDArray 3x4 @cpu(0)>

# Slicing

In [25]:
y[1:3]


[[ 5.3497763  -3.6585288   0.37682867  2.1115074 ]
 [ 6.2896824   7.7905655   1.9706488   2.591093  ]]
<NDArray 2x4 @cpu(0)>

In [26]:
y[0, 1] = 10
print(y)


[[10.569341   10.          3.3407602   1.9659429 ]
 [ 5.3497763  -3.6585288   0.37682867  2.1115074 ]
 [ 6.2896824   7.7905655   1.9706488   2.591093  ]]
<NDArray 3x4 @cpu(0)>


# Broadcasting

In [27]:
a = nd.ones((3, 3))
b = nd.arange(3)
print(a + b)


[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
<NDArray 3x3 @cpu(0)>


# Context

In [28]:
m = nd.ones(shape=(3, 3), ctx=mx.gpu(0))
m


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @gpu(0)>

In [31]:
a_gpu = a.copyto(mx.gpu(0))
a_gpu


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @gpu(0)>

In [32]:
m + a_gpu


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
<NDArray 3x3 @gpu(0)>

In [33]:
m + a_gpu


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
<NDArray 3x3 @gpu(0)>